### ISSUE TITLE
Lỗi hạn thẻ tạm

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalservices#3]
Đã cấu hình Lấy ngày ra viện làm ngày kết thúc hạn thẻ, nhưng khi xuất xml trên admin và gửi tự động vẫn lấy theo giá trị nhập hạn thẻ trên form.
Dữ liệu: dbnhidong_han_the_tam.
Mã BA: 2022003242, Khoa Sơ Sinh
![image](https://user-images.githubusercontent.com/99630883/160737511-6777d0d0-f4f4-4184-8ad1-6d741ecace73.png)
![image](https://user-images.githubusercontent.com/99630883/160737642-3fb7fee6-f02e-41a2-9a61-4f6cfaed8cbb.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Hiện tại đang bắt trong thẻ tạm phải có chữ KT trong đó mới là thẻ tạm. Trường hợp này nó hổng có chữ KT nên hông được coi là thẻ tạm.

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật theo mô tả mới [tại đây](https://github.com/oth-dhghospital/dhg.hospitalservices/commit/577287055cdff27688e2dd172072837a8d38e2ab)
